[build]
input = "src/main.wapl"
output = "target/stddev"
opt = "O2"
clang = "clang"

[release]
input = "src/main.wapl"
output = "target/stddev"
opt = "O3"
clang = "clang"

[wasm]
input = "src/main.wapl"
output = "target/stddev.wasm"
opt = "O1"
clang = "$HOME/wasi-sdk-29.0-x86_64-linux/bin/clang"
bitsize = "32"
sysroot = "$HOME/wasi-sdk-29.0-x86_64-linux/share/wasi-sysroot"
wasm2wat = "wasm2wat"
wat = "src/stddev.wat"
wasmruntime = "/home/hayate/wasmtime-v40.0.0-x86_64-linux/wasmtime"